### PR TITLE
Updated Dockerana to support multiple hosts.

### PR DESCRIPTION
**Pull request by aetherical**
This is in reference to issue #25

When the dockerana container is started, it can either take an environmental variable for the hostname or if not specified
`hostname` will be executed.  However, if inside a container it will likely give the container name rather than the host in which it is running.

### CODE REVIEW

**Comment by schvin** [comment]
LGTM. @cglewis do you have any issue with the addition of the tcp/2003 for carbon? I don't think it is necessary, but may be misinterpreting it's use?

**Comment by cglewis** [comment]
I don't think `tcp/2003` needs to be exposed, since it is used for statsd, which is linked to the carbon container. @aetherical did you have a use case where it needed to be specifically exposed outside of that link?

**Comment by aetherical** [comment]
Yes, I exposed it so that graphite formatted data could be collected in addition to statsd. There are tools/applications which send metrics via graphite but don't speak statsd.

That might be more generic than was the original intent of dockerana, however.

Thanks, 
Matt

On August 5, 2014 1:32:25 PM EDT, Charlie Lewis notifications@github.com wrote:

> I don't think `tcp/2003` needs to be exposed, since it is used for
> statsd, which is linked to the carbon container. @aetherical did you
> have a use case where it needed to be specifically exposed outside of
> that link?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/dockerana/dockerana/pull/31#issuecomment-51231525

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cglewis** [comment]
I'm fine with the inclusion, thanks for the contribution.

**Pull request merged**
